### ISSUE TITLE
飞书文档 分栏(column) 组件里的内容（图片、文本等）无法导出

### ISSUE THREAD

**Issue by GQH123** [Wsine/feishu2md#96]
### 问题描述

飞书文档 分栏(column) 组件里的内容（图片、文本等）无法导出。一开始是用分栏并列的图片没有导出来，后来试了一下只要在分栏组件里的就都导不出来。

这个分栏挺好用的，也很灵活，为了整齐地列出从文档中截的图经常会用到。如果能解决就太好了，辛苦作者。

### 飞书文档链接

https://test-cpndiix9fw2n.feishu.cn/docx/SCHFd0ZsFoDxbJxNN82cmqxAnte?from=from_copylink

### 期望的 markdown 格式

```markdown
见下方
```

### (可选)更多信息

从左到右把分栏里的内容像正常导出 markdown 一样罗列出来就行。如果能在 markdown 里嵌入 html 实现类似分栏的效果就更好了，可能也不太容易。飞书的分栏比较简单，就是并排的几个等高（但不一定等宽）的框，框内有内容。具体请见脱敏文档。

用的最新版 (v2.0.0) feishu2md，环境 Ubuntu 22.04

**Comment by Wsine** [comment]
该功能已实现，请静待新版本发布。

**Comment by GQH123** [comment]
OK，感谢

**Comment by GQH123** [comment]
不好意思再打扰一下作者，好像有个情况没导出来，也是我实际文档里遇到的，在脱敏文档里更新了，对应的是 **Test3** 下的 column。Test1 和 Test2 是对照组，都是没问题的

**Comment by GQH123** [comment]
就是它是第二缩进级别，但是没有标号

**Comment by Wsine** [comment]
请把期望的 markdown 格式源码提供一下。

**Comment by GQH123** [comment]
和之前一样的，能导出来就 ok
> 从左到右把分栏里的内容像正常导出 markdown 一样罗列出来就行。如果能在 markdown 里嵌入 html 实现类似分栏的效果就更好了，可能也不太容易。飞书的分栏比较简单，就是并排的几个等高（但不一定等宽）的框，框内有内容。具体请见脱敏文档。

**Comment by Wsine** [comment]
不同的 markdown 编辑器可能会有不同的行为。冒昧说一句，“能导出就行” 特别像是不负责的产品经理说的话。在开源社区里，我们更倾向于清晰具体的问题和需求，才能讨论和设计具体的解法。

所以，请提供你认为导出合理的 markdown 格式源码。

**Comment by GQH123** [comment]
不好意思，你是之前的那位作者吗？你仔细看过最初的问题描述和脱敏文档吗？我可以再给你描述一遍，一个分栏类似一个小的 markdown 文档，其中可以包含各种 markdown 组件，具体格式按这些组件为准，分栏自身不对应 markdown 格式，明白？

**Comment by GQH123** [comment]
![image](https://github.com/Wsine/feishu2md/assets/26428685/07b7b169-161b-4c1b-a5ec-7ce26fd22357)

![image](https://github.com/Wsine/feishu2md/assets/26428685/580e963c-abc2-4ae3-8b96-f5628491eb9f)

**Comment by Wsine** [comment]
Since you seem to be a researcher, I expressed my points in English to make it clear.

The feishu document presents the following.

<img width="862" alt="image" src="https://github.com/Wsine/feishu2md/assets/8842278/982e0b33-dedc-4338-99c7-fe032e13c7d0">


Are you looking for the markdown output content like the following? Be aware of the space indentation in the markdown source code. 

```md
1. [Training Data Extraction From Pre-trained Language Models: A Survey](http://arxiv.org/abs/2305.16157)

    a. Test 1
    
      ![](https://placebear.com/200/200)

      aaa

      ![](https://placebear.com/200/200)

      bbb
    
    - Test 2

      ![](https://placebear.com/200/200)

      aaa

      ![](https://placebear.com/200/200)

      bbb

    Test 3*
    
      ![](https://placebear.com/200/200)
    
      aaa
    
      ![](https://placebear.com/200/200)

      bbb
    
    - Test 4

      ![](https://placebear.com/200/200)

      aaa

      ![](https://placebear.com/200/200)

      bbb

```

Rendered by Typora, the output appears to be not what was expected.

<img width="752" alt="image" src="https://github.com/Wsine/feishu2md/assets/8842278/66e4a221-9de0-4507-9366-4d06e6b3fe75">

The core reason is that the markdown syntax does not support indentation for paragraphs.

Maybe there are some editors supporting your expected rendering. But those are customized upon the standard.

The above is what I expect you to (and you should) explore for validity before just simply asking for a feature without any effort. This is why I request you to provide your expected markdown source code. 

I may get wrong. If there are any, please advice.

**Comment by GQH123** [comment]
Got it, I really did not realize the problem in advance, sorry. If it's okay, use unordered list to replace paragraph indents please.

**Comment by GQH123** [comment]
In fact what I claimed above is not about paragraph indents, but the column widget under paragraph indent seems to be missing after exporting. Paragraph indent itself is just fine. This is just another problem, though not realized beforehand.
